#-- v3 syntax
version: '2'

services:
  mongodb:
    image: mongo:4.2.6
    container_name: mongodbsky
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_INITDB_DATABASE=skydb
    ports:
      - 27017:27017
    networks:
      - app-network

  nodebackend:
    build: .
    container_name: api-sky
    environment:
      - DB_CONNECT_URI=$DB_CONNECT_URI
      - TOKEN_SECRET=$TOKEN_SECRET
    ports:
      - 6767:6767 # porta default da api
    networks:
      - app-network
    depends_on:
      - mongodb
    command: npm run start


networks:
  app-network:
    driver: bridge

volumes:
  dbdata: